INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1001','Unit Number','unitNumber','KC-SYS','9CD01DC99CD5DF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1002','Descend Flag','subunits','KC-SYS','9CD01DC99CD6DF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1003','Section Name','sectionName','KC-SYS','9CD01DC99CD7DF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1004','Document Action','documentAction','KC-SYS','9CD01DC99CD8DF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1005','Proposal Number','proposal','KC-SYS','9CD01DC99CD9DF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1006','Protocol Number','protocol','KC-SYS','9CD01DC99CDADF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1007','Committee Number','committee','KC-SYS','9CD01DC99CDBDF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1008','Award Number','award','KC-SYS','9CD01DC99CDCDF6CE040DC0A1F8A7146',1)
/
INSERT INTO KRIM_ATTR_DEFN_T (ACTV_IND,CMPNT_NM,KIM_ATTR_DEFN_ID,LBL,NM,NMSPC_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','org.kuali.kra.kim.bo.KcKimAttributes','1009','TimeAndMoney Number','timeandmoney','KC-SYS','9CD01DC99CDDDF6CE040DC0A1F8A7146',1)
/
