select * from protocol;

delete from protocol_correspondence;
delete from protocol_actions;
delete from protocol_attachment_protocol;
delete from protocol_funding_source;
delete from protocol_location;
delete from protocol_notepad;
delete from protocol_onln_rvws;
delete from protocol_attachment_personnel;
delete from protocol_persons;
delete from protocol_research_areas;
delete from comm_schedule_minutes;
delete from protocol_reviewers;
delete from protocol_exempt_number;
delete from protocol_special_review;
delete from protocol_expidited_chklst;
delete from protocol_submission;
delete from protocol_vulnerable_sub;
delete from proto_amend_renew_modules;
delete from proto_amend_renewal;
delete from protocol_risk_levels;
delete from protocol;