select * from organization;
select count(*) from organization;
delete from organization where ORGANIZATION_ID='000426';
select * from organization;
select * from organization where ORGANIZATION_ID is not '000429';
select * from organization where ORGANIZATION_ID!='000429';
select * from organization where ORGANIZATION_ID!='000001';
delete from organization where ORGANIZATION_ID!='000001';
delete from organization_ynq where ORGANIZATION_ID!='000001';
delete from organization where ORGANIZATION_ID!='000001';
delete from iacuc_protocol_location where ORGANIZATION_ID!='000001';
delete from organization where ORGANIZATION_ID!='000001';
delete from protocol_location where ORGANIZATION_ID!='000001';
delete from organization where ORGANIZATION_ID!='000001';
delete from organization_type where ORGANIZATION_ID!='000001';
delete from organization where ORGANIZATION_ID!='000001';
delete from budget_sub_awards where ORGANIZATION_ID!='000001';
select SUBAWARD_NUMBER, BUDGET_ID from budget_sub_award_period_detail where ORGANIZATION_ID!='000001';
delete from organization where ORGANIZATION_ID!='000001';
delete from budget_sub_awards where ORGANIZATION_ID!='000001';
select * from budget_sub_awards where ORGANIZATION_ID!='000001';
select count(*) from budget_sub_awards where ORGANIZATION_ID!='000001';
show create table budget_sub_awards;
delete from budget_sub_awards where ORGANIZATION_ID!='000001';
select SUB_AWARD_NUMBER from budget_sub_awards where ORGANIZATION_ID!='000001';
select SUB_AWARD_NUMBER, BUDGET_ID from budget_sub_awards where ORGANIZATION_ID!='000001';
select ORGANIZATION_ID, SUB_AWARD_NUMBER, BUDGET_ID from budget_sub_awards where ORGANIZATION_ID!='000001';
delete from budget_sub_award_period_detail where SUBAWARD_NUMBER='2' and BUDGET_ID='13';
delete from budget_sub_award_period_detail where SUBAWARD_NUMBER='2' and BUDGET_ID='16';
delete from budget_sub_award_period_detail where SUBAWARD_NUMBER='2' and BUDGET_ID='33';
delete from budget_sub_award_period_detail where SUBAWARD_NUMBER='2' and BUDGET_ID='41';
delete from budget_sub_awards where ORGANIZATION_ID!='000001';
select ORGANIZATION_ID, SUB_AWARD_NUMBER, BUDGET_ID from budget_sub_awards where ORGANIZATION_ID!='000001';
delete from budget_sub_awards where ORGANIZATION_ID!='000001';
select SUB_AWARD_NUMBER, BUDGET_ID from budget_sub_award_files where SUB_AWARD_NUMBER='2';
delete from budget_sub_award_files where SUB_AWARD_NUMBER='2';
delete from budget_sub_awards where ORGANIZATION_ID!='000001';
select SUB_AWARD_NUMBER, BUDGET_ID from budget_details where SUB_AWARD_NUMBER='2';
select SUBAWARD_NUMBER, BUDGET_ID from budget_details where SUBAWARD_NUMBER='2';
delete from budget_details where SUBAWARD_NUMBER='2';
select BUDGET_DETAILS_ID, SUBAWARD_NUMBER, BUDGET_ID from budget_details where SUBAWARD_NUMBER='2';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='76';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='77';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='78';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='79';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='80';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='74';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='75';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='302';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='303';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='304';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='305';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='306';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='388';
delete from budget_details_cal_amts where BUDGET_DETAILS_ID='389';
select BUDGET_DETAILS_ID, SUBAWARD_NUMBER, BUDGET_ID from budget_details where SUBAWARD_NUMBER='2';
delete from budget_details where SUBAWARD_NUMBER='2';

delete from budget_rate_and_base where BUDGET_DETAILS_ID in (select BUDGET_DETAILS_ID from budget_details where SUBAWARD_NUMBER='2');
